### ISSUE TITLE
Error login and password

### ISSUE THREAD

**Issue by guigui91** [ReneNulschDE/ha_link2home#10]
Hello,

I followed the steps, and when it asks for the login and password, I enter my email and the password I use in the LinktoHome Pro app, but it doesn't work. It shows me a "login or password error."

Thanks

**Comment by ReneNulschDE** [comment]
It's developed based on the "Link2home"-app only. I can try to test it but I assume that this is a complete different tech stack.

**Comment by ReneNulschDE** [comment]
I checked the link2home pro app. This app is for a complete different set of newer devices. So this component will not support this. I will adjust the readme to make this more clear.
