### ISSUE TITLE
Please support Shutter

### ISSUE THREAD

**Issue by 0815hoffi** [ReneNulschDE/ha_link2home#8]
![Screenshot_20240808_142454_Link2Home](https://github.com/user-attachments/assets/98c77df8-dd87-445c-b99f-29b380c2db8b)
Can you please add Support for Shutter Switch 

https://www.rev.de/product/0088167090/link2home-rollladenschalter-komplett-mit-rahmen-weiss

Example 

https://github.com/pejonp/mozilla-webthing-link2home

**Comment by ReneNulschDE** [comment]
How did you solve it?

**Comment by 0815hoffi** [comment]
I have created a script Hard Coded without LoginData.
Not pretty but it works.
Maybe you can add it to your integration after all.

https://github.com/0815hoffi/ha_link2home
